<?php

namespace Tests\Feature\V1;

use App\Models\Product;
use App\Models\Role;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class ProductControllerTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        Product::factory(10)->create();
    }


    public function testIndexWithAdminReturnsSuccessResponse()
    {
        $user = User::factory()->create([
            'role_id' => Role::ADMIN_ID
        ]);

        $response = $this->actingAs($user)
            ->get(route('v1.product.index'));

        $response->assertOk()
            ->assertJsonCount(10, 'data.data');

        Product::factory()->create([
            'name' => 'Nuevo producto'
        ]);

        $response = $this->actingAs($user)
            ->get(route('v1.product.index' , [
                'filter' => [
                    'name' => 'nuevo'
                ]
            ]));

        $response->assertOk()
            ->assertJsonCount(1, 'data.data');


    }

    public function testIndexWithUserReturnsSuccessResponse()
    {
        $user = User::factory()->create([
            'role_id' => Role::USER_ID
        ]);

        $response = $this->actingAs($user)
            ->get(route('v1.product.index'));

        $response->assertOk()
            ->assertJsonCount(10, 'data.data');

        Product::factory()->create([
            'name' => 'Nuevo producto'
        ]);

        $response = $this->actingAs($user)
            ->get(route('v1.product.index' , [
                'filter' => [
                    'name' => 'nuevo'
                ]
            ]));

        $response->assertOk()
            ->assertJsonCount(1, 'data.data');

    }

    public function testShowReturnsSuccessResponse()
    {
        $user = User::factory()->create([
            'role_id' => Role::USER_ID
        ]);

        $product = Product::factory()->create();

        $response = $this->actingAs($user)
            ->get(route('v1.product.show', ['product' => $product->id]));

        $response->assertOk()
            ->assertJson([
                'data' => [
                    'id' => $product->id,
                    'name' => $product->name,
                    'description' => $product->description
                ],
                'message' => config('messages.success.show')
            ]);
    }

    public function testShowReturnsErrorResponse()
    {
        $user = User::factory()->create([]);

        $response = $this->actingAs($user)
            ->get(route('v1.product.show', ['product' => 99]));

        $response->assertStatus(404);
    }

    public function testStoreWithUserReturnErrorResponse()
    {
        $user = User::factory()->create([
            'role_id' => Role::USER_ID
        ]);

        $product = Product::factory()->make()->toArray();

        $response = $this->actingAs($user)
            ->post(route('v1.product.store'), $product);

        $response->assertForbidden()
            ->assertJson([
                'message' => 'No posee permisos para acceder a este recurso'
            ]);
    }

    public function testStoreWithAdminReturnsSuccessResponse()
    {
        $user = User::factory()->create([
            'role_id' => Role::ADMIN_ID
        ]);

        $product = Product::factory()->make()->toArray();
        $response = $this->actingAs($user)
            ->post(route('v1.product.store'), $product);

        $response->assertCreated()
            ->assertJson([
                'message' => config('messages.success.store'),
                'data' => $product
            ]);
    }

    public function testUpdateWithUserReturnsErrorResponse()
    {
        $user = User::factory()->create([
            'role_id' => Role::USER_ID
        ]);

        $product = Product::factory()->create();
        $updatedData = ['name' => 'Updated Product'];

        $response = $this->actingAs($user)
            ->put(route('v1.product.update', ['product' => $product->id]), $updatedData);

        $response->assertForbidden()
            ->assertJson([
                'message' => 'No posee permisos para acceder a este recurso'
            ]);
    }

    public function testUpdateWithAdminReturnsSuccessResponse()
    {
        $user = User::factory()->create([
            'role_id' => Role::ADMIN_ID
        ]);

        $product = Product::factory()->create();
        $updatedData = [
            'name' => 'Updated Product',
            ...$product->toArray()
        ];

        $response = $this->actingAs($user)
            ->put(route('v1.product.update', ['product' => $product->id]), $updatedData);

        $response->assertOk()
            ->assertJson([
                'message' => config('messages.success.update'),
                'data' => [
                    'id' => $product->id,
                    'name' => 'Updated Product'
                ]
            ]);
    }

    public function testDeleteWithUserReturnsErrorResponse()
    {
        $user = User::factory()->create([
            'role_id' => Role::USER_ID
        ]);

        $product = Product::factory()->create();

        $response = $this->actingAs($user)
            ->delete(route('v1.product.destroy', ['product' => $product->id]));

        $response->assertForbidden()
            ->assertJson([
                'message' => 'No posee permisos para acceder a este recurso'
            ]);
    }

    public function testDeleteWithAdminReturnsSuccessResponse()
    {
        $user = User::factory()->create([
            'role_id' => Role::ADMIN_ID
        ]);

        $product = Product::factory()->create();

        $response = $this->actingAs($user)
            ->delete(route('v1.product.destroy', ['product' => $product->id]));

        $response->assertOk()
            ->assertJson([
                'message' => config('messages.success.delete'),
                'data' => []
            ]);
    }
}
